export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ONE_QUESTION = 'GET_ONE_QUESTION';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';