export const USER_INIT = 'USER_INIT';
export const LOGIN = 'LOGIN';
export const FAVORITE_QUESTION = 'FAVORITE_QUESTION';
export const UNFAVORITE_QUESTION = 'UNFAVORITE_QUESTION';
export const ADD_QUESTION_TO_ASKED = 'ADD_QUESTION_TO_ASKED';
export const REMOVE_QUESTION_FROM_ASKED = 'REMOVE_QUESTION_FROM_ASKED';